---
- hosts: web
  remote_user: ec2-user
  become: yes
  vars:
    packages:
    - name: prometheus
      image: prom/prometheus
      port: 9090:9090
    - name: node-exporter
      image: prom/node-exporter
      port: 9100:9100
    - name: grafana
      image: grafana/grafana
      port: 3000:3000
  tasks:
  - name: install docker
    yum:
      name: docker
      state: latest
  - name: start docker
    service:
      name: docker
      state: started
      enabled: true
  - name: pull images "{{ item.name }}"
    docker_image:
      name: "{{ item.image }}"
      state: present
      source: pull
    loop: "{{ packages }}"
  - name: install "{{ item.name }}"
    docker_container:
      name: "{{ item.name }}"
      image: "{{ item.image }}"
      published_ports: "{{ item.port }}"
      detach: yes
      restart_policy: always
    loop: "{{ packages }}"
